INSERT INTO ingredients (canonical_name, display_name, display_name_plural, aliases) VALUES
-- Vegetables (very common)
('capsicum', 'capsicum', 'capsicums', ARRAY['bell pepper', 'bell peppers', 'pepper', 'sweet pepper']),
('eggplant', 'eggplant', 'eggplants', ARRAY['aubergine', 'egg plant']),
('zucchini', 'zucchini', 'zucchinis', ARRAY['courgette']),
('rocket', 'rocket', 'rocket', ARRAY['arugula']),
('shallot', 'shallot', 'shallots', ARRAY['shallots', 'eschalot', 'eschalots']),
('spring onion', 'spring onion', 'spring onions', ARRAY['scallion', 'green onion', 'spring onions']),
('coriander', 'coriander', 'coriander', ARRAY['cilantro']),
('swede', 'swede', 'swedes', ARRAY['rutabaga', 'rutabagas']),
('beetroot', 'beetroot', 'beetroots', ARRAY['beet']),
('silverbeet', 'silverbeet', 'silverbeets', ARRAY['swiss chard', 'chard']),
('pumpkin', 'pumpkin', 'pumpkins', ARRAY['squash', 'winter squash']),
('sweet potato', 'sweet potato', 'sweet potatoes', ARRAY['yam', 'yams']),
('potato', 'potato', 'potatoes', ARRAY['potatoes']),
('tomato', 'tomato', 'tomatoes', ARRAY['tomatoes']),
('onion', 'onion', 'onions', ARRAY['onions']),
('garlic', 'clove of garlic', 'cloves of garlic', ARRAY['garlic cloves', 'clove of garlic']),
('fresh ginger', 'piece of ginger', 'piece of ginger', ARRAY['fresh ginger', 'ginger root', 'knob of ginger']),
('carrot', 'carrot', 'carrots', ARRAY['carrots']),
('celery', 'stick of celery', 'sticks of celery', ARRAY['celery stalk', 'celery stick']),
('leek', 'leek', 'leek', ARRAY['leeks']),
('cauliflower', 'cauliflower', 'cauliflower', ARRAY['cauliflower head']),
('broccoli', 'broccoli', 'broccoli', ARRAY['broccoli florets']),
('mushroom', 'mushroom', 'mushroom', ARRAY['mushrooms']),
('spinach', 'spinach', 'spinach', ARRAY['baby spinach']),
('baby spinach', 'baby spinach', 'baby spinach', ARRAY['baby spinach']),
('lettuce', 'head of lettuce', 'heads of lettuce', ARRAY['lettuce leaves']),
('cabbage', 'cabbage', 'cabbage', ARRAY['green cabbage', 'white cabbage']),
('red onion', 'red onion', 'red onion', ARRAY['purple onion']),

-- Herbs
('parsley', 'parsley', 'parsley', ARRAY['flat-leaf parsley', 'italian parsley', 'curly parsley']),
('basil', 'basil', 'basil', ARRAY['sweet basil']),
('thyme', 'thyme', 'thyme', ARRAY['fresh thyme']),
('rosemary', 'rosemary', 'rosemary', ARRAY['fresh rosemary']),
('sage', 'sage', 'sage', ARRAY['fresh sage']),
('dill', 'dill', 'dill', ARRAY['fresh dill']),
('mint', 'mint', 'mint', ARRAY['fresh mint']),
('oregano', 'oregano', 'oregano', ARRAY['fresh oregano']),
('bay leaf', 'bay leaf', 'bay leaf', ARRAY['bay leaves']),

-- Fruit
('lemon', 'lemon', 'lemon', ARRAY['lemons']),
('lime', 'lime', 'lime', ARRAY['limes']),
('orange', 'orange', 'orange', ARRAY['oranges']),
('apple', 'apple', 'apple', ARRAY['apples']),
('pear', 'pear', 'pear', ARRAY['pears']),
('banana', 'banana', 'banana', ARRAY['bananas']),
('avocado', 'avocado', 'avocado', ARRAY['avocados']),
('pineapple', 'pineapple', 'pineapple', ARRAY['pineapple chunks']),
('mango', 'mango', 'mango', ARRAY['mangoes']),
('strawberry', 'strawberry', 'strawberry', ARRAY['strawberries']),
('blueberry', 'blueberry', 'blueberry', ARRAY['blueberries']),

-- Meat & seafood
('beef mince', 'beef mince', 'beef mince', ARRAY['ground beef', 'minced beef']),
('pork mince', 'pork mince', 'pork mince', ARRAY['ground pork', 'minced pork']),
('chicken breast', 'chicken breast', 'chicken breast', ARRAY['chicken breasts']),
('chicken thigh', 'chicken thigh', 'chicken thigh', ARRAY['chicken thighs']),
('whole chicken', 'whole chicken', 'whole chicken', ARRAY['roasting chicken']),
('lamb mince', 'lamb mince', 'lamb mince', ARRAY['ground lamb', 'minced lamb']),
('lamb leg', 'lamb leg', 'lamb leg', ARRAY['leg of lamb']),
('bacon', 'bacon', 'bacon', ARRAY['streaky bacon', 'rashers']),
('ham', 'ham', 'ham', ARRAY['cooked ham']),
('pork belly', 'pork belly', 'pork belly', ARRAY['pork belly slab']),
('sausages', 'sausages', 'sausages', ARRAY['sausage', 'links']),
('salmon', 'salmon', 'salmon', ARRAY['salmon fillet', 'salmon fillets']),
('tuna', 'tuna', 'tuna', ARRAY['fresh tuna']),
('prawns', 'prawns', 'prawns', ARRAY['shrimp']),

-- Dairy & eggs
('milk', 'milk', 'milk', ARRAY['full cream milk', 'whole milk']),
('cream', 'cream', 'cream', ARRAY['heavy cream', 'double cream']),
('sour cream', 'sour cream', 'sour cream', ARRAY['soured cream']),
('yoghurt', 'yoghurt', 'yoghurt', ARRAY['yogurt', 'greek yoghurt', 'greek yogurt']),
('butter', 'butter', 'butter', ARRAY['unsalted butter', 'salted butter']),
('cheddar cheese', 'cheddar cheese', 'cheddar cheese', ARRAY['cheddar']),
('parmesan', 'parmesan', 'parmesan', ARRAY['parmigiano reggiano', 'parmesan cheese']),
('mozzarella', 'mozzarella', 'mozzarella', ARRAY['fresh mozzarella']),
('feta', 'feta', 'feta', ARRAY['feta cheese']),
('ricotta', 'ricotta', 'ricotta', ARRAY['ricotta cheese']),
('cream cheese', 'cream cheese', 'cream cheese', ARRAY['soft cheese']),
('eggs', 'eggs', 'eggs', ARRAY['egg']),

-- Pantry / dry goods
('olive oil', 'olive oil', 'olive oil', ARRAY['extra virgin olive oil', 'evoo']),
('vegetable oil', 'vegetable oil', 'vegetable oil', ARRAY['canola oil', 'rapeseed oil']),
('sunflower oil', 'sunflower oil', 'sunflower oil', ARRAY['sunflower seed oil']),
('flour', 'flour', 'flour', ARRAY['plain flour', 'all-purpose flour']),
('self-raising flour', 'self-raising flour', 'self-raising flour', ARRAY['self-rising flour']),
('baking powder', 'baking powder', 'baking powder', ARRAY['baking soda']),
('sugar', 'sugar', 'sugar', ARRAY['white sugar', 'granulated sugar']),
('caster sugar', 'caster sugar', 'caster sugar', ARRAY['superfine sugar']),
('brown sugar', 'brown sugar', 'brown sugar', ARRAY['light brown sugar', 'dark brown sugar']),
('icing sugar', 'icing sugar', 'icing sugar', ARRAY['powdered sugar', 'confectioners sugar']),
('rice', 'rice', 'rice', ARRAY['white rice', 'long grain rice']),
('basmati rice', 'basmati rice', 'basmati rice', ARRAY['basmati']),
('jasmine rice', 'jasmine rice', 'jasmine rice', ARRAY['jasmine']),
('pasta', 'pasta', 'pasta', ARRAY['dry pasta']),
('breadcrumbs', 'breadcrumbs', 'breadcrumbs', ARRAY['bread crumbs']),
('stock', 'stock', 'stock', ARRAY['broth']),
('chicken stock', 'chicken stock', 'chicken stock', ARRAY['chicken broth']),
('beef stock', 'beef stock', 'beef stock', ARRAY['beef broth']),
('vegetable stock', 'vegetable stock', 'vegetable stock', ARRAY['vegetable broth']),
('coconut milk', 'coconut milk', 'coconut milk', ARRAY['coconut cream']),
('soy sauce', 'soy sauce', 'soy sauce', ARRAY['soya sauce']),
('fish sauce', 'fish sauce', 'fish sauce', ARRAY['nam pla']),
('vinegar', 'vinegar', 'vinegar', ARRAY['white vinegar']),
('apple cider vinegar', 'apple cider vinegar', 'apple cider vinegar', ARRAY['cider vinegar']),
('balsamic vinegar', 'balsamic vinegar', 'balsamic vinegar', ARRAY['balsamic']),
('mustard', 'mustard', 'mustard', ARRAY['dijon mustard', 'yellow mustard']),
('tomato paste', 'tomato paste', 'tomato paste', ARRAY['tomato purée']),
('tomato sauce', 'tomato sauce', 'tomato sauce', ARRAY['ketchup']),
('passata', 'passata', 'passata', ARRAY['tomato passata', 'strained tomatoes']),

-- Spices & aromatics
('salt', 'salt', 'salt', ARRAY['sea salt', 'table salt']),
('pepper', 'pepper', 'pepper', ARRAY['black pepper', 'ground pepper']),
('paprika', 'paprika', 'paprika', ARRAY['smoked paprika']),
('cumin', 'cumin', 'cumin', ARRAY['ground cumin']),
('coriander seed', 'coriander seed', 'coriander seed', ARRAY['ground coriander']),
('turmeric', 'turmeric', 'turmeric', ARRAY['ground turmeric']),
('cinnamon', 'cinnamon', 'cinnamon', ARRAY['ground cinnamon']),
('nutmeg', 'nutmeg', 'nutmeg', ARRAY['ground nutmeg']),
('chilli', 'chilli', 'chilli', ARRAY['chili', 'chilli pepper', 'chile']),
('chilli flakes', 'chilli flakes', 'chilli flakes', ARRAY['red pepper flakes']),

('garam masala', 'garam masala', 'garam masala', ARRAY['garam masala spice mix']);
