// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ingredientparser.proto

package ingredientparser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message
type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           string                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_ingredientparser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingredientparser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_ingredientparser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

// Response message
type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []*ConfidenceText      `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Size          *ConfidenceText        `protobuf:"bytes,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Amount        []*Amount              `protobuf:"bytes,3,rep,name=amount,proto3" json:"amount,omitempty"`
	Preparation   *ConfidenceText        `protobuf:"bytes,4,opt,name=preparation,proto3,oneof" json:"preparation,omitempty"`
	Comment       *ConfidenceText        `protobuf:"bytes,5,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Purpose       *ConfidenceText        `protobuf:"bytes,6,opt,name=purpose,proto3,oneof" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_ingredientparser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingredientparser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_ingredientparser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetName() []*ConfidenceText {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ParseResponse) GetSize() *ConfidenceText {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *ParseResponse) GetAmount() []*Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *ParseResponse) GetPreparation() *ConfidenceText {
	if x != nil {
		return x.Preparation
	}
	return nil
}

func (x *ParseResponse) GetComment() *ConfidenceText {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *ParseResponse) GetPurpose() *ConfidenceText {
	if x != nil {
		return x.Purpose
	}
	return nil
}

// Helper messages
type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      string                 `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Approximate   bool                   `protobuf:"varint,5,opt,name=approximate,proto3" json:"approximate,omitempty"`
	Singular      bool                   `protobuf:"varint,6,opt,name=singular,proto3" json:"singular,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_ingredientparser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_ingredientparser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_ingredientparser_proto_rawDescGZIP(), []int{2}
}

func (x *Amount) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Amount) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Amount) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Amount) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Amount) GetApproximate() bool {
	if x != nil {
		return x.Approximate
	}
	return false
}

func (x *Amount) GetSingular() bool {
	if x != nil {
		return x.Singular
	}
	return false
}

type ConfidenceText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfidenceText) Reset() {
	*x = ConfidenceText{}
	mi := &file_ingredientparser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceText) ProtoMessage() {}

func (x *ConfidenceText) ProtoReflect() protoreflect.Message {
	mi := &file_ingredientparser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceText.ProtoReflect.Descriptor instead.
func (*ConfidenceText) Descriptor() ([]byte, []int) {
	return file_ingredientparser_proto_rawDescGZIP(), []int{3}
}

func (x *ConfidenceText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConfidenceText) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_ingredientparser_proto protoreflect.FileDescriptor

const file_ingredientparser_proto_rawDesc = "" +
	"\n" +
	"\x16ingredientparser.proto\" \n" +
	"\fParseRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\tR\x03raw\"\xc8\x02\n" +
	"\rParseResponse\x12#\n" +
	"\x04name\x18\x01 \x03(\v2\x0f.ConfidenceTextR\x04name\x12(\n" +
	"\x04size\x18\x02 \x01(\v2\x0f.ConfidenceTextH\x00R\x04size\x88\x01\x01\x12\x1f\n" +
	"\x06amount\x18\x03 \x03(\v2\a.AmountR\x06amount\x126\n" +
	"\vpreparation\x18\x04 \x01(\v2\x0f.ConfidenceTextH\x01R\vpreparation\x88\x01\x01\x12.\n" +
	"\acomment\x18\x05 \x01(\v2\x0f.ConfidenceTextH\x02R\acomment\x88\x01\x01\x12.\n" +
	"\apurpose\x18\x06 \x01(\v2\x0f.ConfidenceTextH\x03R\apurpose\x88\x01\x01B\a\n" +
	"\x05_sizeB\x0e\n" +
	"\f_preparationB\n" +
	"\n" +
	"\b_commentB\n" +
	"\n" +
	"\b_purpose\"\xaa\x01\n" +
	"\x06Amount\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\tR\bquantity\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12 \n" +
	"\vapproximate\x18\x05 \x01(\bR\vapproximate\x12\x1a\n" +
	"\bsingular\x18\x06 \x01(\bR\bsingular\"D\n" +
	"\x0eConfidenceText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence2<\n" +
	"\x10IngredientParser\x12(\n" +
	"\x05Parse\x12\r.ParseRequest\x1a\x0e.ParseResponse\"\x00B1Z/github.com/Kupfy/feeds-crawler/ingredientparserb\x06proto3"

var (
	file_ingredientparser_proto_rawDescOnce sync.Once
	file_ingredientparser_proto_rawDescData []byte
)

func file_ingredientparser_proto_rawDescGZIP() []byte {
	file_ingredientparser_proto_rawDescOnce.Do(func() {
		file_ingredientparser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingredientparser_proto_rawDesc), len(file_ingredientparser_proto_rawDesc)))
	})
	return file_ingredientparser_proto_rawDescData
}

var file_ingredientparser_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ingredientparser_proto_goTypes = []any{
	(*ParseRequest)(nil),   // 0: ParseRequest
	(*ParseResponse)(nil),  // 1: ParseResponse
	(*Amount)(nil),         // 2: Amount
	(*ConfidenceText)(nil), // 3: ConfidenceText
}
var file_ingredientparser_proto_depIdxs = []int32{
	3, // 0: ParseResponse.name:type_name -> ConfidenceText
	3, // 1: ParseResponse.size:type_name -> ConfidenceText
	2, // 2: ParseResponse.amount:type_name -> Amount
	3, // 3: ParseResponse.preparation:type_name -> ConfidenceText
	3, // 4: ParseResponse.comment:type_name -> ConfidenceText
	3, // 5: ParseResponse.purpose:type_name -> ConfidenceText
	0, // 6: IngredientParser.Parse:input_type -> ParseRequest
	1, // 7: IngredientParser.Parse:output_type -> ParseResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ingredientparser_proto_init() }
func file_ingredientparser_proto_init() {
	if File_ingredientparser_proto != nil {
		return
	}
	file_ingredientparser_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingredientparser_proto_rawDesc), len(file_ingredientparser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingredientparser_proto_goTypes,
		DependencyIndexes: file_ingredientparser_proto_depIdxs,
		MessageInfos:      file_ingredientparser_proto_msgTypes,
	}.Build()
	File_ingredientparser_proto = out.File
	file_ingredientparser_proto_goTypes = nil
	file_ingredientparser_proto_depIdxs = nil
}
