// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: ingredientparser.proto

package ingredientparser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngredientParser_Parse_FullMethodName = "/IngredientParser/Parse"
)

// IngredientParserClient is the client API for IngredientParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition
type IngredientParserClient interface {
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type ingredientParserClient struct {
	cc grpc.ClientConnInterface
}

func NewIngredientParserClient(cc grpc.ClientConnInterface) IngredientParserClient {
	return &ingredientParserClient{cc}
}

func (c *ingredientParserClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, IngredientParser_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngredientParserServer is the server API for IngredientParser service.
// All implementations must embed UnimplementedIngredientParserServer
// for forward compatibility.
//
// The service definition
type IngredientParserServer interface {
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	mustEmbedUnimplementedIngredientParserServer()
}

// UnimplementedIngredientParserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngredientParserServer struct{}

func (UnimplementedIngredientParserServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedIngredientParserServer) mustEmbedUnimplementedIngredientParserServer() {}
func (UnimplementedIngredientParserServer) testEmbeddedByValue()                          {}

// UnsafeIngredientParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngredientParserServer will
// result in compilation errors.
type UnsafeIngredientParserServer interface {
	mustEmbedUnimplementedIngredientParserServer()
}

func RegisterIngredientParserServer(s grpc.ServiceRegistrar, srv IngredientParserServer) {
	// If the following call pancis, it indicates UnimplementedIngredientParserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngredientParser_ServiceDesc, srv)
}

func _IngredientParser_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngredientParserServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngredientParser_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngredientParserServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngredientParser_ServiceDesc is the grpc.ServiceDesc for IngredientParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngredientParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IngredientParser",
	HandlerType: (*IngredientParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _IngredientParser_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingredientparser.proto",
}
